name: Publish to Pub.dev
on: 
  push :
    branches:
    - stable
jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main # required!
        
      - name: 'GeekyAnts Gauges Flutter'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIALLS_JSON }}
