name: Publish to Pub.dev
on: 
  push :
    branches:
    - main
    - stable
    - dev
jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@main # required!
        
      - name: 'GAUGES FLUTTER'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: ${{ secrets.CREDENTIALLS_JSON }}