name: PR-Checks

on:
  workflow_dispatch:
  pull_request:
    branches: [ main , develop ]

jobs:
  check:
    name: PR

    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3


      - name: 🖥️ Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.7.7'
         

      - name: ⬇️ Install dependencies
        run: dart pub get

      - name: 🛠 Disable font smoothing
        run: defaults -currentHost write -g AppleFontSmoothing -int 0

      - name: 🧪 Test
        run: flutter test

      - name: 🛠 Enable font smoothing
        run: defaults -currentHost write -g AppleFontSmoothing -int 3
